# Project Info
sonar.projectKey=backend
sonar.projectName=backend
sonar.projectVersion=1.0

# Source Code Location
sonar.sources=.

# Python specific settings
sonar.language=py
sonar.sourceEncoding=UTF-8

# SonarQube Server
sonar.host.url=http://localhost:9000
sonar.token=sqp_263dd428da32bbc836df474d7f3a3d8e1b888ee3

# Exclusions (important)
sonar.exclusions=venv/**,__pycache__/**,.pyc,.pyo,*.pyd,.pytest_cache/**,migrations/**

# Optional: Test configuration
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

# Optional: Coverage report (if using pytest-cov)
sonar.python.coverage.reportPaths=coverage.xml
