/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#3adfac',
        error: '#ba1a1a',
        'on-primary-fixed': '#002116',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'on-secondary-fixed': '#001e2f',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#d3e4fe',
        'on-secondary': '#ffffff',
        tertiary: '#904d00',
        'surface-bright': '#f8f9ff',
        'secondary-fixed-dim': '#89ceff',
        'tertiary-fixed-dim': '#ffb77b',
        outline: '#6c7a73',
        'surface-container-high': '#dce9ff',
        'surface-variant': '#d3e4fe',
        'on-error-container': '#93000a',
        secondary: '#006591',
        'on-error': '#ffffff',
        'tertiary-fixed': '#ffdcc2',
        background: '#f8f9ff',
        'on-tertiary-container': '#683700',
        'on-primary-fixed-variant': '#00513b',
        'on-primary-container': '#004d38',
        'secondary-container': '#39b8fd',
        'on-background': '#0b1c30',
        'inverse-on-surface': '#eaf1ff',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-container': '#e5eeff',
        'outline-variant': '#bacac1',
        'secondary-fixed': '#c9e6ff',
        'tertiary-container': '#ff972f',
        'on-tertiary-fixed-variant': '#6d3900',
        surface: '#f8f9ff',
        'on-tertiary-fixed': '#2e1500',
        'on-surface-variant': '#3c4a43',
        'on-secondary-fixed-variant': '#004c6e',
        'inverse-surface': '#213145',
        'primary-fixed': '#60fcc7',
        'primary-container': '#00c897',
        'surface-dim': '#cbdbf5',
        'on-surface': '#0b1c30',
        primary: '#006c50',
        'surface-tint': '#006c50',
        'primary-fixed-dim': '#3adfac',
        'on-secondary-container': '#004666',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      boxShadow: {
        'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
        'card': '0 4px 30px rgba(0, 0, 0, 0.1)',
      },
      backdropBlur: {
        glass: '12px',
      },
      animation: {
        'pulse-subtle': 'pulse-subtle 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        'pulse-subtle': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
